export default {
  LOGO_COLOR_WHITE: '#c8c1a5',
  LOGO_COLOR_WHITE_BACKGROUND: '#f5f0dc',
  LOGO_COLOR_GREEN: '#74785d',
  LOGO_COLOR_GREEN_BACKGROUND: '#cbcfb4',
  LOGO_COLOR_BROWN: '#8f6349',
  THEME_MAIN_COLOR: '#8f6349',
};
